### ISSUE TITLE
Open API: create schemas for viewport path parameters.

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-zoning-api#225]
# Description
Mapbox vector tile endpoints will have path parameters to request tiles at the specified zoom, x, and y. We what to create reusable schemas for these parameters. A example of the general structure for these parameters is available on the [132/on-demand-tilesets](https://github.com/NYCPlanning/ae-zoning-api/tree/132/on-demand-tilesets) branch. Though, the example incorrectly describes them as strings.

[example viewportParam](https://github.com/NYCPlanning/ae-zoning-api/blob/f2508c4d1059b35b1e5e295c10566545094c7982/openapi/openapi.yaml#L396)

## Acceptance Criteria
- [ ] viewport schemas are created under `components/parameters`
- [ ] Zoom param is created
- [ ] X param is created
- [ ] Y param is created

## Helper code
Copy and paste this into [`components/parameters`](https://github.com/NYCPlanning/ae-zoning-api/blob/f2508c4d1059b35b1e5e295c10566545094c7982/openapi/openapi.yaml#L394). It has the configuration that was already written on the prototype branch, updated to define them as numbers

```yaml
    viewportZoomParam:
      name: z
      in: path
      description: viewport zoom component
      required: true
      schema:
        type: integer
        example: 7
    viewportXParam:
      name: x
      in: path
      description: viewport x component
      required: true
      schema:
        type: integer
        example: 1000
    viewportYParam:
      name: y
      in: path
      description: viewport y component
      required: true
      schema:
        type: integer
        example: 1000
```
