### ISSUE TITLE
Upgrade kubb version to allow nullable type for capital project category

### ISSUE THREAD

**Issue by pratishta** [NYCPlanning/ae-zoning-api#321]
In order to allow a capital project category to be nullable, we can define it in the [Open API schema](https://swagger.io/docs/specification/data-models/enums/) like so: 

```
CapitalProjectCategory:
      type: string
      nullable: true
      enum:
        - Fixed Asset
        - Lump Sum
        - ITT, Vehicles and Equipment
        - null
      description: The type of Capital Project.
```

However Kubb generates a type and Zod schema that turns null into a string option for the category enum:
```
export const capitalProjectCategorySchema = z.enum([
  `Fixed Asset`,
  `Lump Sum`,
  `ITT, Vehicles and Equipment`,
  `null`,
]);
```
This Kubb issue has been documented before [here](https://github.com/kubb-labs/kubb/issues/919) and [here](https://github.com/kubb-labs/kubb/issues/1030). So this ticket will have Kubb upgraded to [v 2.19.6](https://github.com/kubb-labs/kubb/pull/1039) since that's the version that includes the latest fix for this problem. 

#### Acceptance criteria
- [x] Update kubb packages to 2.19.6 in package.json
- [x] Address compatibility issues with rest of code
